### ISSUE TITLE
Quivers ignore infinity enchantment

### ISSUE THREAD

**Issue by Tomatobird8** [Nyfaria/NyfsQuiver#2]
Quivers use up an arrow even if the bow has the infinity enchantment which should prevent arrows from being removed from the stack.

Tested on Fabric 1.17 with these mods installed:
* nyfsquivers-Fabric-0.2.2-1.17
* trinkets-3.0.0
* fabric-api-0.35.1+1.17
* wraith-waystones-2.0.1

Video: https://streamable.com/dgsl4n

**Comment by Nyfaria** [comment]
I will have an update soon to fix this.

**Comment by Nyfaria** [comment]
This should be fixed if you update.
