### ISSUE TITLE
[1.16.5] Crash with CoFH Core

### ISSUE THREAD

**Issue by farinc** [Nyfaria/NyfsQuiver#6]
There appears be a mixin crash with CoFH Core and their changes with archery related stuff. [crash](https://gist.github.com/farinc/a4a5ac7f6c9b4988af34f2de1802acca). To reproduce, open a new world with just CoFH Core, Curios, and this mod and attempt to use a bow with any arrow. Perhaps its their end?

**Comment by Nyfaria** [comment]
fixed in most recent version
