### ISSUE TITLE
[Feature Request] Config option to use Curios 'back' slot instead of dedicated quiver slot

### ISSUE THREAD

**Issue by paintballkev812** [Nyfaria/NyfsQuiver#7]
First off, I want to say I really enjoy this mod. I would like to request to have a config option to use the standard 'back' slot for the quiver instead of the dedicate quiver slot. I am using a couple of other mods that use the back slot, and would like to restrict equipped items to only one back item (i.e. A player could equip a backpack or a quiver, but not both). I feel like this option would allow this mod to better integrate with the others.

**Comment by Nyfaria** [comment]
I'm working on a side quiver option.

**Comment by Nyfaria** [comment]
Also, Curios are datapacked.
So you could make a datapack for your server that changes the Quivers to use the back slot and remove the quiver slot.

**Comment by paintballkev812** [comment]
A side quiver would be interesting. I was not aware I could go the datapack route. I will look into this. Thanks

**Comment by Intaria** [comment]
> Also, Curios are datapacked. So you could make a datapack for your server that changes the Quivers to use the back slot and remove the quiver slot.

Could you plz explain how to do it?
I would also like to change the curios identifier from "quiver" to "back"
